#!/usr/bin/env python3
"""
Stage 10X: audit all 47 resource evidence families and create a common
within-resource 0..1 evidence strength for bonus/luxury resources.

Strategic resources already have *_EVIDENCE_RAW, *_STRENGTH and
*_CANDIDATE_QTY generated by the strategic-candidate stage; those are audited
but not recomputed here.

No cross-resource comparison of physical magnitudes is made. Percentiles are
computed independently within each resource among positive-evidence hexes.

This is still pre-placement: no gameplay thinning and no one-resource-per-hex
conflict resolution.
"""
from __future__ import annotations
import argparse,json
from pathlib import Path
import numpy as np
import pandas as pd
import geopandas as gpd

STRATEGIC=["HORSES","IRON","NITER","COAL","OIL","ALUMINUM","URANIUM"]

BONUS=[
 "BANANAS","BISON","CATTLE","DEER","FISH","SHEEP","STONE","WHEAT","MAIZE","RICE"
]
LUXURY=[
 "CITRUS","COCOA","COPPER","COTTON","CRAB","DYES","FURS","GEMS","GOLD",
 "INCENSE","IVORY","MARBLE","PEARLS","SALT","SILK","SILVER","SPICES","SUGAR",
 "TRUFFLES","WHALES","WINE","COFFEE","TEA","TOBACCO","OLIVES","PERFUME",
 "AMBER","JADE","LAPIS_LAZULI","CORAL"
]

def num(df,c):
    if c not in df.columns:
        raise RuntimeError(f"required evidence column missing: {c}")
    return pd.to_numeric(df[c],errors="coerce").fillna(0).clip(lower=0)

def pct_positive(x):
    x=pd.to_numeric(x,errors="coerce").fillna(0).clip(lower=0)
    out=pd.Series(0.0,index=x.index,dtype="float64")
    pos=x.gt(0)
    if pos.any():
        out.loc[pos]=x.loc[pos].rank(method="average",pct=True)
    return out

def raw_for(df,rid):
    # Quantitative crop area.
    spam={
      "BANANAS":"BANANAS_SPAM_HA","CITRUS":"CITRUS_SPAM_HA",
      "COCOA":"COCOA_SPAM_HA","COTTON":"COTTON_SPAM_HA",
      "SUGAR":"SUGAR_SPAM_HA","COFFEE":"COFFEE_SPAM_HA",
      "TEA":"TEA_SPAM_HA","TOBACCO":"TOBACCO_SPAM_HA",
      "WHEAT":"WHEAT_SPAM_HA","MAIZE":"MAIZE_SPAM_HA","RICE":"RICE_SPAM_HA",
    }
    if rid in spam:
        return num(df,spam[rid]),spam[rid]

    mon={
      "SPICES":"SPICES_MONFREDA_HA",
      "WINE":"WINE_MONFREDA_HA",
      "OLIVES":"OLIVES_MONFREDA_HA",
    }
    if rid in mon:
        return num(df,mon[rid]),mon[rid]

    # Livestock density: combine mean with a small local-maximum term.
    if rid in {"CATTLE","SHEEP"}:
        p=rid
        mean=num(df,f"{p}_GLW_MEAN")
        mx=num(df,f"{p}_GLW_MAX")
        raw=np.log1p(mean)+0.20*np.log1p(mx)
        return pd.Series(raw,index=df.index),f"log1p({p}_GLW_MEAN)+0.20*log1p({p}_GLW_MAX)"

    # PHYLACINE range richness; mean coverage dominates.
    if rid in {"BISON","DEER","FURS","IVORY","WHALES"}:
        mean=num(df,f"{rid}_PHYLACINE_MEAN_RICHNESS")
        mx=num(df,f"{rid}_PHYLACINE_MAX_RICHNESS")
        raw=mean+0.20*mx
        return pd.Series(raw,index=df.index),f"{rid}_PHYLACINE_MEAN_RICHNESS+0.20*MAX_RICHNESS"

    # OBIS occurrence evidence. log1p record-count fields were already retained
    # specifically as evidence strength, not biological abundance.
    if rid in {"FISH","CRAB","PEARLS"}:
        mean=num(df,f"{rid}_OBIS_LOGN_MEAN")
        mx=num(df,f"{rid}_OBIS_LOGN_MAX")
        grids=num(df,f"{rid}_OBIS_GRID_N")
        raw=mean+0.20*mx+0.05*np.log1p(grids)
        return pd.Series(raw,index=df.index),f"{rid}_OBIS_LOGN_MEAN+0.20*MAX+0.05*log1p(GRID_N)"

    mrds={
      "STONE":"STONE_MRDS_SCORE","COPPER":"COPPER_MRDS_SCORE",
      "GEMS":"GEMS_MRDS_SCORE","GOLD":"GOLD_MRDS_SCORE",
      "MARBLE":"MARBLE_MRDS_SCORE","SALT":"SALT_MRDS_SCORE",
      "SILVER":"SILVER_MRDS_SCORE",
    }
    if rid in mrds:
        return num(df,mrds[rid]),mrds[rid]

    doc={
      "DYES":"DYES_DOC_SCORE","INCENSE":"INCENSE_DOC_SCORE",
      "SILK":"SILK_DOC_SCORE","TRUFFLES":"TRUFFLES_DOC_SCORE",
      "PERFUME":"PERFUME_DOC_SCORE","AMBER":"AMBER_DOC_SCORE",
      "JADE":"JADE_DOC_SCORE","LAPIS_LAZULI":"LAPIS_LAZULI_DOC_SCORE",
    }
    if rid in doc:
        return num(df,doc[rid]),doc[rid]

    if rid=="CORAL":
        return num(df,"CORAL_WCMC_SCORE"),"CORAL_WCMC_SCORE"

    raise RuntimeError(f"no evidence mapping for {rid}")

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("board")
    ap.add_argument("--layer",default=None)
    ap.add_argument("--prefix",default="CIV_GAME_MAP_STAGE10X_ALL_RESOURCE_STRENGTH")
    a=ap.parse_args()

    board=gpd.read_file(a.board,layer=a.layer) if a.layer else gpd.read_file(a.board)
    if len(board)!=261635 or not board.id.is_unique:
        raise RuntimeError("canonical board audit failed")

    audit=[]
    for rid in STRATEGIC:
        for c in [f"{rid}_EVIDENCE_RAW",f"{rid}_STRENGTH",f"{rid}_CANDIDATE_QTY"]:
            if c not in board.columns:
                raise RuntimeError(f"strategic field missing: {c}")
        raw=num(board,f"{rid}_EVIDENCE_RAW")
        strength=num(board,f"{rid}_STRENGTH").clip(0,1)
        qty=num(board,f"{rid}_CANDIDATE_QTY")
        if not raw.gt(0).any():
            raise RuntimeError(f"{rid}: zero strategic evidence")
        audit.append({
          "resource":rid,"class":"strategic",
          "raw_formula":f"{rid}_EVIDENCE_RAW (precomputed)",
          "evidence_hexes":int(raw.gt(0).sum()),
          "strength_positive_hexes":int(strength.gt(0).sum()),
          "candidate_qty_positive_hexes":int(qty.gt(0).sum()),
          "raw_max":float(raw.max()),
          "strength_max":float(strength.max()),
        })

    for rid,klass in [(r,"bonus") for r in BONUS]+[(r,"luxury") for r in LUXURY]:
        raw,formula=raw_for(board,rid)
        raw=pd.to_numeric(raw,errors="coerce").fillna(0).clip(lower=0)
        if not raw.gt(0).any():
            raise RuntimeError(f"{rid}: zero mapped evidence using {formula}")
        strength=pct_positive(raw)
        board[f"{rid}_FINAL_EVIDENCE_RAW"]=raw
        board[f"{rid}_FINAL_STRENGTH"]=strength
        audit.append({
          "resource":rid,"class":klass,"raw_formula":formula,
          "evidence_hexes":int(raw.gt(0).sum()),
          "raw_max":float(raw.max()),
          "strength_min_positive":float(strength[strength.gt(0)].min()),
          "strength_median_positive":float(strength[strength.gt(0)].median()),
          "strength_max":float(strength.max()),
        })

    expected=set(STRATEGIC+BONUS+LUXURY)
    got={r["resource"] for r in audit}
    if got!=expected:
        raise RuntimeError(f"catalog mismatch missing={sorted(expected-got)} extra={sorted(got-expected)}")

    board.to_file(
      a.prefix+".gpkg",layer="game_map_stage10x_all_resource_strength",driver="GPKG"
    )

    scorecols=["id","SURFACE"]
    for rid in STRATEGIC:
        scorecols += [f"{rid}_EVIDENCE_RAW",f"{rid}_STRENGTH",f"{rid}_CANDIDATE_QTY"]
    for rid in BONUS+LUXURY:
        scorecols += [f"{rid}_FINAL_EVIDENCE_RAW",f"{rid}_FINAL_STRENGTH"]
    board[scorecols].to_csv(a.prefix+"_SCORES.csv",index=False)

    adf=pd.DataFrame(audit)
    adf.to_csv(a.prefix+"_AUDIT.csv",index=False)
    summary={
      "stage":"10X",
      "resource_count":len(audit),
      "expected_resource_count":47,
      "class_counts":adf["class"].value_counts().to_dict(),
      "all_resources_have_positive_evidence":bool((adf.evidence_hexes>0).all()),
      "normalization":"within-resource percentile among positive evidence only",
      "cross_resource_physical_magnitude_comparison":False,
      "final_placement":False,
      "gameplay_thinning_applied":False,
      "one_resource_per_hex_enforced":False,
      "audit":audit,
      "Stage1A_1deg_used":False,
    }
    Path(a.prefix+"_SUMMARY.json").write_text(json.dumps(summary,indent=2),encoding="utf-8")
    print(json.dumps(summary,indent=2))

if __name__=="__main__":
    main()
